# Generated by Django 3.2.1 on 2021-07-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crudapp',
            new_name='crud',
        ),
    ]
